name: 'birdwatcher'
services:
  nextjs:
    build: .
    ports:
      - '${BIRDS_PORT}:3000'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/birdsdb
    networks:
      - database
      - public

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: birdsdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - database
    expose:
    - ${POSTGRES_PORT}
    command: -p ${POSTGRES_PORT}

  pgadmin:
    image: dpage/pgadmin4
    # profiles:
    #   - donotstart
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '${PGADMIN_PORT}:80'
    depends_on:
      - db
    networks:
      - database
      - public

volumes:
  postgres_data:

networks:
  database:
    internal: true
  public:
    driver: bridge
